"""add language to post

Revision ID: 21c5eab8fe6c
Revises: d88d2a06ae3d
Create Date: 2019-08-24 17:53:22.057500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c5eab8fe6c'
down_revision = 'd88d2a06ae3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
